// Output created by jacc on Fri Jul 31 10:19:07 CST 2020

package Compiler.Jacc;

public interface ParserTokens {
    int ENDINPUT = 0;
    int AMARILLO = 1;
    int APARECETORTUGA = 2;
    int AT = 3;
    int AV = 4;
    int AVANZA = 5;
    int AZAR = 6;
    int AZUL = 7;
    int BAJALAPIZ = 8;
    int BL = 9;
    int BLANCO = 10;
    int BORRAPANTALLA = 11;
    int CENTRO = 12;
    int CIAN = 13;
    int COS = 14;
    int CUENTA = 15;
    int DIFERENCIA = 16;
    int DIVISION = 17;
    int EJECUTA = 18;
    int ELEGIR = 19;
    int ELEMENTO = 20;
    int ESPERA = 21;
    int FIN = 22;
    int FLOAT = 23;
    int GD = 24;
    int GI = 25;
    int GIRADERECHA = 26;
    int GIRAIZQUIERDA = 27;
    int GRIS = 28;
    int IDENTIFIER = 29;
    int IGUALES = 30;
    int INC = 31;
    int INIC = 32;
    int INTEGER = 33;
    int MARRON = 34;
    int MAYORQUE = 35;
    int MENORQUE = 36;
    int MENOS = 37;
    int NEGRO = 38;
    int O = 39;
    int OCULTATORTUGA = 44;
    int OT = 46;
    int PARA = 48;
    int PONCL = 49;
    int PONCOLORLAPIZ = 50;
    int PONPOS = 51;
    int PONRUMBO = 52;
    int PONX = 53;
    int PONXY = 54;
    int PONY = 55;
    int POTENCIA = 56;
    int PRIMERO = 57;
    int PROCEDURE_NAME = 58;
    int PRODUCTO = 63;
    int RAIZCUADRADA = 64;
    int RC = 65;
    int RE = 66;
    int REDONDEA = 67;
    int REPITE = 68;
    int RESTO = 69;
    int RETROCEDE = 70;
    int ROJO = 71;
    int RUMBO = 72;
    int SB = 73;
    int SEN = 74;
    int SENO = 75;
    int SI = 76;
    int SUBELAPIZ = 77;
    int SUMA = 78;
    int UL = 79;
    int ULTIMO = 80;
    int VAR = 81;
    int VERDE = 82;
    int Y = 83;
    int error = 84;
    // '(' (code=40)
    // ')' (code=41)
    // '*' (code=42)
    // '+' (code=43)
    // '-' (code=45)
    // '/' (code=47)
    // ';' (code=59)
    // '<' (code=60)
    // '=' (code=61)
    // '>' (code=62)
    // '[' (code=91)
    // ']' (code=93)
}
