// Output created by jacc on Sun Jul 12 15:03:22 CST 2020

package Compiler;

interface ParserTokens {
    int ENDINPUT = 0;
    int AMARILLO = 1;
    int APARECETORTUGA = 2;
    int AT = 3;
    int AV = 4;
    int AVANZA = 5;
    int AZAR = 6;
    int AZUL = 7;
    int BAJALAPIZ = 8;
    int BL = 9;
    int BLANCO = 10;
    int BORRAPANTALLA = 11;
    int CENTRO = 12;
    int CIAN = 13;
    int COS = 14;
    int CUENTA = 15;
    int DIFERENCIA = 16;
    int DIVISION = 17;
    int EJECUTA = 18;
    int ELEGIR = 19;
    int ELEMENTO = 20;
    int ESPERA = 21;
    int FLOAT = 22;
    int GD = 23;
    int GI = 24;
    int GIRADERECHA = 25;
    int GIRAIZQUIERZA = 26;
    int GRIS = 27;
    int IDENTIFIER = 28;
    int IGUALES = 29;
    int INC = 30;
    int INIC = 31;
    int INTEGER = 32;
    int MARRON = 33;
    int MAYORQUE = 34;
    int MENORQUE = 35;
    int MENOS = 36;
    int NEGRO = 37;
    int O = 38;
    int OCULTARTORTUGA = 39;
    int OT = 44;
    int PONCL = 46;
    int PONCOLORLAPIZ = 48;
    int PONPOS = 49;
    int PONRUMBO = 50;
    int PONX = 51;
    int PONXY = 52;
    int PONY = 53;
    int POTENCIA = 54;
    int PRIMERO = 55;
    int PRODUCTO = 56;
    int RAIZCUADRADA = 57;
    int RC = 58;
    int RE = 63;
    int REDONDEA = 64;
    int REPITE = 65;
    int RESTO = 66;
    int RETROCEDE = 67;
    int ROJO = 68;
    int RUMBO = 69;
    int SB = 70;
    int SEN = 71;
    int SENO = 72;
    int SI = 73;
    int SUBELAPIZ = 74;
    int SUMA = 75;
    int UL = 76;
    int ULTIMO = 77;
    int VAR = 78;
    int VERDE = 79;
    int Y = 80;
    int error = 81;
    // '(' (code=40)
    // ')' (code=41)
    // '*' (code=42)
    // '+' (code=43)
    // '-' (code=45)
    // '/' (code=47)
    // ';' (code=59)
    // '<' (code=60)
    // '=' (code=61)
    // '>' (code=62)
    // '[' (code=91)
    // ']' (code=93)
}
