/* The following code was generated by JFlex 1.4.3 on 16/7/20 18:02 */

package Compiler.NewLex;
import Compiler.Jacc.ParserTokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/7/20 18:02 from the specification file
 * <tt>C:/Users/Marlo/IdeaProjects/Logorduin/src/Compiler/NewLex/flexer.jflex</tt>
 */
public class NewLexer implements ParserTokens {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\30\0\1\7\1\0\1\15"+
    "\1\15\1\5\1\12\1\0\1\15\1\14\1\4\1\10\10\11\1\13"+
    "\1\0\1\15\1\15\1\15\1\15\1\0\1\7\32\6\1\15\1\0"+
    "\1\15\1\0\1\7\1\0\1\17\1\34\1\23\1\40\1\32\1\7"+
    "\1\30\1\41\1\21\1\35\1\7\1\26\1\33\1\22\1\24\1\31"+
    "\1\42\1\20\1\37\1\27\1\25\1\16\1\7\1\43\1\44\1\36"+
    "\1\0\1\7\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\2\5\1\3\1\5"+
    "\12\1\1\2\4\0\1\6\1\7\2\0\1\10\3\0"+
    "\1\11\1\12\1\13\3\0\1\14\1\0\1\15\2\0"+
    "\1\16\1\17\21\0\1\20\4\0\1\21\1\22\5\0"+
    "\1\23\11\0\1\24\2\0\1\25\25\0\1\26\4\0"+
    "\1\27\3\0\1\30\1\0\1\31\10\0\1\32\6\0"+
    "\1\33\1\34\1\35\1\36";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\45\0\157\0\45\0\224\0\271"+
    "\0\336\0\271\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc"+
    "\0\u01e1\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a\0\u02bf\0\271"+
    "\0\u02e4\0\u0309\0\u032e\0\45\0\u0353\0\u0378\0\u039d\0\u03c2"+
    "\0\u03e7\0\u040c\0\45\0\u0431\0\45\0\u0456\0\u047b\0\u04a0"+
    "\0\45\0\u04c5\0\45\0\u04ea\0\u050f\0\u02e4\0\45\0\u0534"+
    "\0\u0559\0\u057e\0\u05a3\0\u05c8\0\u05ed\0\u0612\0\u0637\0\u065c"+
    "\0\u0681\0\u06a6\0\u06cb\0\u06f0\0\u0715\0\u073a\0\u075f\0\u0784"+
    "\0\45\0\u07a9\0\u07ce\0\u07f3\0\u0818\0\45\0\45\0\u083d"+
    "\0\u0862\0\u0887\0\u08ac\0\u08d1\0\45\0\u08f6\0\u091b\0\u0940"+
    "\0\u0965\0\u098a\0\u09af\0\u09d4\0\u09f9\0\u0a1e\0\45\0\u0a43"+
    "\0\u0a68\0\45\0\u0a8d\0\u0ab2\0\u0ad7\0\u0afc\0\u0b21\0\u0b46"+
    "\0\u0b6b\0\u0b90\0\u0bb5\0\u0bda\0\u0bff\0\u0c24\0\u0c49\0\u0c6e"+
    "\0\u0c93\0\u0cb8\0\u0cdd\0\u0d02\0\u0d27\0\u0d4c\0\u0d71\0\45"+
    "\0\u0d96\0\u0dbb\0\u0de0\0\u0e05\0\45\0\u0e2a\0\u0e4f\0\u0e74"+
    "\0\45\0\u0e99\0\45\0\u0ebe\0\u0ee3\0\u0f08\0\u0f2d\0\u0f52"+
    "\0\u0f77\0\u0f9c\0\u0fc1\0\45\0\u0fe6\0\u100b\0\u1030\0\u1055"+
    "\0\u107a\0\u109f\0\45\0\45\0\45\0\45";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\11\1\12\1\13\1\2\1\6\1\14\1\15\1\16"+
    "\1\17\1\2\1\20\1\21\3\2\1\22\1\23\2\2"+
    "\1\24\2\2\1\25\5\2\47\0\1\4\46\0\1\26"+
    "\1\27\45\0\4\7\1\0\1\7\2\0\27\7\10\0"+
    "\1\30\1\0\2\30\1\31\40\0\2\11\1\0\1\11"+
    "\41\0\1\13\1\11\1\30\1\13\1\31\47\0\1\32"+
    "\43\0\1\33\10\0\1\34\1\0\1\35\40\0\1\36"+
    "\4\0\1\37\34\0\1\40\54\0\1\41\35\0\1\42"+
    "\3\0\1\43\36\0\1\44\16\0\1\45\30\0\1\46"+
    "\37\0\1\47\4\0\1\50\1\0\1\51\43\0\1\52"+
    "\6\0\1\53\10\0\1\26\1\3\1\4\42\26\5\54"+
    "\1\55\37\54\10\0\2\56\1\0\1\56\51\0\1\57"+
    "\43\0\1\60\44\0\1\61\60\0\1\62\40\0\1\63"+
    "\36\0\1\64\45\0\1\65\47\0\1\66\37\0\1\67"+
    "\46\0\1\70\57\0\1\71\27\0\1\72\60\0\1\73"+
    "\10\0\5\54\1\74\37\54\4\0\1\4\1\55\61\0"+
    "\1\75\42\0\1\76\60\0\1\77\30\0\1\100\47\0"+
    "\1\101\50\0\1\102\43\0\1\103\35\0\1\104\45\0"+
    "\1\105\22\0\1\106\1\107\17\0\1\110\45\0\1\111"+
    "\56\0\1\112\12\0\4\54\1\4\1\74\37\54\36\0"+
    "\1\113\40\0\1\114\36\0\1\115\44\0\1\116\40\0"+
    "\1\117\53\0\1\120\36\0\1\121\16\0\1\122\31\0"+
    "\1\123\45\0\1\124\35\0\1\125\53\0\1\126\35\0"+
    "\1\127\50\0\1\130\44\0\1\131\45\0\1\132\37\0"+
    "\1\133\63\0\1\134\40\0\1\135\45\0\1\136\30\0"+
    "\1\137\56\0\1\140\32\0\1\141\57\0\1\142\44\0"+
    "\1\143\41\0\1\144\57\0\1\145\22\0\1\146\60\0"+
    "\1\147\41\0\1\150\32\0\1\151\56\0\1\152\42\0"+
    "\1\153\55\0\1\154\30\0\1\155\45\0\1\156\51\0"+
    "\1\157\36\0\1\160\41\0\1\161\45\0\1\162\43\0"+
    "\1\163\47\0\1\164\52\0\1\165\32\0\1\166\45\0"+
    "\1\167\46\0\1\170\57\0\1\171\35\0\1\172\53\0"+
    "\1\173\26\0\1\174\53\0\1\175\47\0\1\176\53\0"+
    "\1\177\22\0\1\200\54\0\1\201\42\0\1\202\37\0"+
    "\1\203\43\0\1\204\53\0\1\205\43\0\1\206\47\0"+
    "\1\207\54\0\1\210\32\0\1\211\46\0\1\212\33\0"+
    "\1\213\44\0\1\214\44\0\1\215\44\0\1\216\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4292];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\20\1\4\0"+
    "\1\1\1\11\2\0\1\1\3\0\1\11\1\1\1\11"+
    "\3\0\1\11\1\0\1\11\2\0\1\1\1\11\21\0"+
    "\1\11\4\0\2\11\5\0\1\11\11\0\1\11\2\0"+
    "\1\11\25\0\1\11\4\0\1\11\3\0\1\11\1\0"+
    "\1\11\10\0\1\11\6\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    public int line;
    public int column;
    public int currentToken; //Para obtener el token actual sin avanzar el parseo

    public int getCurrentToken() {
        return this.currentToken;
    }

    public int getCurrentLine() {
        return this.line;
    }

    public int getCurrentColumn() {
        return this.column;
    }

    public int prepare(int token) {
        lexeme = yytext();
        currentToken = token;
        return token;
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NewLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public NewLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Integer yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { return prepare(FLOAT);
          }
        case 31: break;
        case 3: 
          { String token = yytext();
    lexeme = token;
    char tokenValue = token.charAt(0);
    currentToken = tokenValue;
    return currentToken;
          }
        case 32: break;
        case 7: 
          { return prepare(AT);
          }
        case 33: break;
        case 2: 
          { /* Ignore */
          }
        case 34: break;
        case 11: 
          { return prepare(GD);
          }
        case 35: break;
        case 9: 
          { return prepare(OT);
          }
        case 36: break;
        case 6: 
          { return prepare(AV);
          }
        case 37: break;
        case 17: 
          { return prepare(PONX);
          }
        case 38: break;
        case 30: 
          { return prepare(APARECETORTUGA);
          }
        case 39: break;
        case 27: 
          { return prepare(OCULTARTORTUGA);
          }
        case 40: break;
        case 8: 
          { return prepare(RE);
          }
        case 41: break;
        case 23: 
          { return prepare(RETROCEDE);
          }
        case 42: break;
        case 16: 
          { return prepare(INIC);
          }
        case 43: break;
        case 22: 
          { return prepare(PONRUMBO);
          }
        case 44: break;
        case 20: 
          { return prepare(AVANZA);
          }
        case 45: break;
        case 29: 
          { return prepare(BORRAPANTALLA);
          }
        case 46: break;
        case 19: 
          { return prepare(RUMBO);
          }
        case 47: break;
        case 26: 
          { return prepare(GIRADERECHA);
          }
        case 48: break;
        case 25: 
          { return prepare(SUBELAPIZ);
          }
        case 49: break;
        case 1: 
          { /* TODO: manejar errores */
          }
        case 50: break;
        case 24: 
          { return prepare(BAJALAPIZ);
          }
        case 51: break;
        case 28: 
          { return prepare(GIRAIZQUIERZA);
          }
        case 52: break;
        case 18: 
          { return prepare(PONY);
          }
        case 53: break;
        case 13: 
          { return prepare(SB);
          }
        case 54: break;
        case 12: 
          { return prepare(BL);
          }
        case 55: break;
        case 10: 
          { return prepare(GI);
          }
        case 56: break;
        case 5: 
          { return prepare(INTEGER);
          }
        case 57: break;
        case 21: 
          { return prepare(CENTRO);
          }
        case 58: break;
        case 4: 
          { return prepare(IDENTIFIER);
          }
        case 59: break;
        case 15: 
          { return prepare(VAR);
          }
        case 60: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
